Cleanup all our scripts here. Die in more places as appropriate, such as if we are totally unable to complete an action for all backends. Properly quote "$@" when calling the main() function.  Make use of debug_msg().
git-svn-id: file:///tank/backups/everglades/var/svn/creandus@179 1c067ae2-9913-0410-8806-fa90ff404265

diff --git a/trunk/dynusers/bash/add.bash.in b/trunk/dynusers/bash/add.bash.in
--- a/trunk/dynusers/bash/add.bash.in
+++ b/trunk/dynusers/bash/add.bash.in
@@ -17,18 +17,19 @@ main() {
 	# Read the command line arguments.
 	local eusers=${1} egroups=${2} pkgname=${3} userspace=${4} root=${5:-/}
 
-	[[ -z "${pkgname}" || -z "${userspace}" ]] \
-		|| die "Script expects 4 arguments: \"new users\"" \
-			"\"new groups\" pkgname userspace"
+	[[ -z "${pkgname}" ]] && die "missing required arg: pkgname"
+	[[ -z "${userspace}" ]] && die "missing required arg: userspace"
 
-	for i in ${egroups} ; do
-		"${SCRIPTDIR}/addgroup.bash" "${i}" "${pkgname}" \
-			"${userspace}" "${root}"
+	for x in ${egroups} ; do
+		"${SCRIPTDIR}/addgroup.bash" "${x}" "${pkgname}" \
+			"${userspace}" "${root}" \
+			|| die "addgroup ${x} failed"
 	done
 
-	for i in ${eusers} ; do
-		"${SCRIPTDIR}/adduser.bash" "${i}" "${pkgname}" \
-			"${userspace}" "${root}"
+	for x in ${eusers} ; do
+		"${SCRIPTDIR}/adduser.bash" "${x}" "${pkgname}" \
+			"${userspace}" "${root}" \
+			|| die "adduser ${x} failed"
 	done
 }
 
@@ -37,5 +38,5 @@ if [[ "${1}" == "--test" ]] ; then
 	exit 0
 fi
 
-main $@
+main "$@"
 # vim: ts=4 :
diff --git a/trunk/dynusers/bash/addgroup.bash.in b/trunk/dynusers/bash/addgroup.bash.in
--- a/trunk/dynusers/bash/addgroup.bash.in
+++ b/trunk/dynusers/bash/addgroup.bash.in
@@ -13,25 +13,23 @@ SCRIPTDIR=${SCRIPTDIR:-@SCRIPTDIR@}
 . "${SCRIPTDIR}/common/config.bash" || exit 1
 . "${SCRIPTDIR}/common/functions.bash" || exit 1
 
-# We make use of egetent. 
+# We make use of egetent.
 . "${SCRIPTDIR}/common/getent.bash" || exit 1
 # Reads the proper data file for the desired group
 . "${SCRIPTDIR}/common/read_groupdata.bash" || exit 1
 
 main() {
 	# Read the command line arguments.
+	# Currently, we expect the following:
+	local newgroup=${1} pkgname=${2} userspace=${3} root=${4}
 
-	# The only options recognized now are the group to be added, the 
-	# package which is asking for the adding, and the userspace type (e.g. 
-	# GNU, fbsd, etc)
-	local newgroup=${1} pkgname=${2} userspace=${3} root=${4:-/}
-
-	[[ -z "${newgroup}" || -z "${pkgname}" || -z "${userspace}" \
-	|| -z "${root}" ]] \
-	&& die "Script expects 4 arguments: groupname pkgname userspace root"
+	[[ -z "${newgroup}" ]] && die "missing required arg: group_name"
+	[[ -z "${pkgname}" ]] && die "missing required arg: pkgname"
+	[[ -z "${userspace}" ]] && die "missing required arg: userspace"
+	[[ -z "${root}" ]] && die "missing required arg: root"
 
 	# Set our default action. Will be either "add" or "mod" by the end.
-	action="add"
+	local action="add"
 
 	###
 	eval `read_groupdata "${newgroup}"`
@@ -64,47 +62,51 @@ main() {
 		local getentinfo=$(egetent group "${newgroup}")
 		
 		local currgid=$(echo ${getentinfo} | cut -d: -f3)
+
 		if [[ ${currgid} -ne ${groupid} ]] ; then
-			echo "The group ${newgroup} needs some values changed."
-			echo "We're doing so now."
+			debug_msg "The group ${newgroup} needs some values changed." \
+				"We're doing so now."
 			action="mod"
 		else
 			# Now, since we've made the proper arrangements for any 
 			# possible changes, we now add the current package name 
 			# to the database and call it quits
-			echo "We already have a group named ${newgroup}." \
+			debug_msg "We already have a group named ${newgroup}." \
 				"Nothing to do." 1>&2
 
 			"${SCRIPTDIR}/db.bash" add group "${pkgname}" \
 				"${newgroup}" "${userspace}"
-
 			exit 0
 		fi
 	fi
 
-	if [[ -f "${DBDIR}/group/${newgroup}" ]] ; then
-		echo "Group ${newgroup} was previously added by this script," >&2
-		echo "but it no longer exists on the system. We'll re-add" >&2
-		echo "them now, but you should have used the users-config" >&2
-		echo "tool to cleanly remove it." >&2
-		echo >&2
+	if [[ -f "${DBDIR}/group/${newgroup}" && -n "${DEBUG}" ]] ; then
+		echo "Group ${newgroup} was previously added by this script," \
+			"but it no longer exists" 1>&2
+		echo "on the system. We'll re-add them now, but you should" \
+			"have used the" 1>&2
+		echo "users-config tool to cleanly remove it." 1>&2
 	fi
 
 	# Finally, we take take the necessary action, either via groupmod 
 	# or groupadd [or it's comparable friends]
+	local done_once
+
 	for x in ${GROUP_BACKENDS}; do
 		if [[ -e "${SCRIPTDIR}/auth/${x}-${userspace}-group${action}.bash" ]] 
 		then
-			echo "Running ${x}-${userspace}-group${action}..."
+			done_once="yes"
+			debug_msg "Running ${x}-${userspace}-group${action}..."
 			. "${SCRIPTDIR}/auth/${x}-${userspace}-group${action}.bash"
 			"${x}-${userspace}-group${action}" "${groupid}" "${newgroup}" \
 				"${root}" || die "group${action} failed"
 		else
-			echo -n "Auth backend ${x} with " >&2
-			echo -n "userspace ${userspace} " >&2
-			echo "not supported by this script." >&2
+			echo "$0: Auth backend ${x} with userspace ${userspace} not" \
+				"supported by this script." 1>&2
 		fi
 	done
+
+	[[ -z "${done_once}" ]] && die "Found no workable backends to run"
 
 	# Properly update the dynamic groups database
 	"${SCRIPTDIR}/db.bash" add group "${pkgname}" "${newgroup}" "${userspace}"
@@ -115,5 +117,5 @@ if [[ "${1}" == "--test" ]] ; then
 	exit 0
 fi
 
-main $@
+main "$@"
 # vim: ts=4 :
diff --git a/trunk/dynusers/bash/adduser.bash.in b/trunk/dynusers/bash/adduser.bash.in
--- a/trunk/dynusers/bash/adduser.bash.in
+++ b/trunk/dynusers/bash/adduser.bash.in
@@ -13,24 +13,20 @@ SCRIPTDIR=${SCRIPTDIR:-@SCRIPTDIR@}
 . "${SCRIPTDIR}/common/config.bash" || exit 1
 . "${SCRIPTDIR}/common/functions.bash" || exit 1
 
-# Read the proper data file for the desired user
-. "${SCRIPTDIR}/common/read_userdata.bash" || exit 1
-# We make use of egetent:
+# We make use of egetent.
 . "${SCRIPTDIR}/common/getent.bash" || exit 1
+# Reads the proper data file for the desired user
+. "${SCRIPTDIR}/common/read_userdata.bash" || exit 1
 
 main() {
 	# Read the command line arguments.
-
-	# The only options recognized now are the user to be added, the 
-	# package which is asking for the adding, and the userspace type (e.g. 
-	# GNU, fbsd, etc)
+	# Currently, we expect the following:
 	local newuser=${1} pkgname=${2} userspace=${3} root=${4}
 
-	if [[ -z "${newuser}" || -z "${pkgname}" || -z "${userspace}" \
-	|| -z "${root}" ]] ; then
-		echo "Script expects 4 arguments: username pkgname userspace root" >&2
-		exit 1
-	fi
+	[[ -z "${newuser}" ]] && die "missing required arg: user_name"
+	[[ -z "${pkgname}" ]] && die "missing required arg: pkgname"
+	[[ -z "${userspace}" ]] && die "missing required arg: userspace"
+	[[ -z "${root}" ]] && die "missing required arg: root"
 
 	# Set our default action. Will be either "add" or "mod" by the end.
 	local action="add"
@@ -61,7 +57,7 @@ main() {
 	if [[ ${newuser} == $(egetent passwd "${newuser}" | cut -d: -f1) ]]
 	then
 		# TODO: If there needs to be some change made, note it
-		# properly, for the user to take care of later with
+		# properly, for the operator to take care of later with
 		# the eselect tool
 		local getentinfo=$(egetent passwd "${newuser}")
 		
@@ -71,20 +67,21 @@ main() {
 		local currgroups=$(id -Gn "${newuser}" |sed 's/ /\n/'| sort -u)
 		local usergroups_sort=$(echo "${usergroups}" |sed 's/,/\n/' |sort -u)
 		local currcomment=$(echo ${getentinfo} |cut -d: -f5)
+		
 		if [[ ${curruid} -ne ${userid} 
 		|| "${currshell}" != "${usershell}"
 		|| "${currhome}" != "${userhome}"
 		|| "${currgroups}" != "${usergroups_sort}"
 		|| "${currcomment}" != "${usercomment}" ]] ; then
-			echo "The user ${newuser} needs some values changed."
-			echo "We're doing so now."
+			debug_msg "The user ${newuser} needs some values changed." \
+				"We're doing so now."
 			action="mod"
 		else
 			# Now, since we've made the proper arrangements for any 
 			# possible changes, we now add the current package name 
 			# to the database and call it quits
-			echo -n "We already have a user named ${newuser}." >&2
-			echo " Nothing to do." >&2
+			debug_msg "We already have a user named ${newuser}." \
+				"Nothing to do." 1>&2
 
 			"${SCRIPTDIR}/db.bash" add user "${pkgname}" \
 				"${newuser}" "${userspace}"
@@ -92,29 +89,34 @@ main() {
 		fi
 	fi
 
-	if [[ -f "${DBDIR}/user/${newuser}" ]] ; then
+	if [[ -f "${DBDIR}/user/${newuser}" && -n "${DEBUG}" ]] ; then
 		echo "User ${newuser} was previously added by this script," \
 			"but it no longer exists" 1>&2
 		echo "on the system. We'll re-add them now, but you should" \
 			"have used the" 1>&2
-		echo "users-config tool to cleanly remove them." 1>&2
+		echo "users-config tool to cleanly remove it." 1>&2
 	fi
 
 	# Finally, we take take the necessary action, either via usermod 
 	# or useradd [or it's comparable friends]
+	local done_once
+
 	for x in ${PASSWD_BACKENDS}; do
 		if [[ -e "${SCRIPTDIR}/auth/${x}-${userspace}-user${action}.bash" ]] 
 		then
-			echo "Running ${x}-${userspace}-user${action}..."
+			done_once="yes"
+			debug_msg "Running ${x}-${userspace}-user${action}..."
 			. "${SCRIPTDIR}/auth/${x}-${userspace}-user${action}.bash"
 			"${x}-${userspace}-user${action}" "${userhome}" "${usergroups}" \
 				"${usershell}" "${userid}" "${usercomment}" "${username}" \
 				"${root}" || die "user${action} failed"
 		else
-			echo "Auth backend ${x} with userspace ${userspace}" \
-			"not supported by this script." 1>&2
+			echo "$0: Auth backend ${x} with userspace ${userspace} not" \
+				"supported by this script." 1>&2
 		fi
 	done
+
+	[[ -z "${done_once}" ]] && die "Found no workable backends to run"
 
 	# Properly update the dynamic users database
 	"${SCRIPTDIR}/db.bash" add user "${pkgname}" "${newuser}" "${userspace}"
@@ -125,5 +127,5 @@ if [[ "${1}" == "--test" ]] ; then
 	exit 0
 fi
 
-main $@
+main "$@"
 # vim: ts=4 :
diff --git a/trunk/dynusers/bash/delgroup.bash.in b/trunk/dynusers/bash/delgroup.bash.in
--- a/trunk/dynusers/bash/delgroup.bash.in
+++ b/trunk/dynusers/bash/delgroup.bash.in
@@ -15,29 +15,37 @@ SCRIPTDIR=${SCRIPTDIR:-@SCRIPTDIR@}
 main() {
 	# Read the command line arguments.
 	# Currently, we expect the following:
-	local deadgroup=${1} userspace=${2} root=${3:-/}
-	# XXX: Make sure we verify our command line args here.
+	local deadgroup=${1} userspace=${2} root=${3}
+	[[ -z "${deadgroup}" ]] && die "missing required arg: user_name"
+	[[ -z "${userspace}" ]] && die "missing required arg: userspace"
+	[[ -z "${root}" ]] && die "missing required arg: root"
 
 	# first, verify that the user to be deleted can be safely deleted
 	[[ -s ${DBDIR}/group/${deadgroup} ]] \
 		&& die "Group ${deadgroup} is still in use by some other" \
 			"package. Not removing."
 
+	# Now, we take the necessary action
+	local done_once
+
 	for x in ${GROUP_BACKENDS} ; do
 		if [[ -e "${SCRIPTDIR}/auth/${x}-${userspace}-groupdel.bash" ]]
 		then
-			echo "Running ${x}-${userspace}-groupdel..."
+			done_once="yes"
+			debug_msg "Running ${x}-${userspace}-groupdel..."
 			. "${SCRIPTDIR}/auth/${x}-${userspace}-groupdel.bash"
 			"${x}-${userspace}-groupdel" "${deadgroup}" "${root}" \
 				|| die "groupdel failed"
 		else
-			echo "Auth backend ${x} with userspace ${userspace}" \
-				"not supported by this script." >&2
+			echo "$0: Auth backend ${x} with userspace ${userspace} not" \
+				"supported by this script." 1>&2
 		fi
 	done
 
+	[[ -z "${done_once}" ]] && die "Found no workable backends to run"
+
 	# Remove the empty database file
-	rm ${DBDIR}/group/${deadgroup}
+	rm "${DBDIR}"/group/${deadgroup}
 }
 
 if [[ "${1}" == "--test" ]] ; then
@@ -45,5 +53,5 @@ if [[ "${1}" == "--test" ]] ; then
 	exit 0
 fi
 
-main $@
+main "$@"
 # vim: ts=4 :
diff --git a/trunk/dynusers/bash/deluser.bash.in b/trunk/dynusers/bash/deluser.bash.in
--- a/trunk/dynusers/bash/deluser.bash.in
+++ b/trunk/dynusers/bash/deluser.bash.in
@@ -15,29 +15,37 @@ SCRIPTDIR=${SCRIPTDIR:-@SCRIPTDIR@}
 main() {
 	# Read the command line arguments.
 	# Currently, we expect the following:
-	local deaduser=${1} userspace=${2} root=${3:-/}
-	# XXX: Make sure we verify our command line args here.
+	local deaduser=${1} userspace=${2} root=${3}
+	[[ -z "${deaduser}" ]] && die "missing required arg: user_name"
+	[[ -z "${userspace}" ]] && die "missing required arg: userspace"
+	[[ -z "${root}" ]] && die "missing required arg: root"
 
 	# first, verify that the user to be deleted can be safely deleted
 	[[ -s ${DBDIR}/user/${deaduser} ]] \
 		&& die "Group ${deaduser} is still in use by some other" \
 			"package. Not removing."
 
+	# Now, we take the necessary action
+	local done_once
+
 	for x in ${PASSWD_BACKENDS} ; do
 		if [[ -e "${SCRIPTDIR}/auth/${x}-${userspace}-userdel.bash" ]]
 		then
-			echo "Running ${x}-${userspace}-userdel..."
+			done_once="yes"
+			debug_msg "Running ${x}-${userspace}-userdel..."
 			. "${SCRIPTDIR}/auth/${x}-${userspace}-userdel.bash"
 			"${x}-${userspace}-userdel" "${deaduser}" "${root}" \
 				|| die "userdel failed"
 		else
-			echo "Auth backend ${x} with userspace ${userspace}" \
-				"not supported by this script." >&2
+			echo "$0: Auth backend ${x} with userspace ${userspace} not" \
+				"supported by this script." 1>&2
 		fi
 	done
 
+	[[ -z "${done_once}" ]] && die "Found no workable backends to run"
+
 	# Remove the empty database file
-	rm ${DBDIR}/user/${deaduser}
+	rm "${DBDIR}"/user/${deaduser}
 }
 
 if [[ "${1}" == "--test" ]] ; then
@@ -45,5 +53,5 @@ if [[ "${1}" == "--test" ]] ; then
 	exit 0
 fi
 
-main $@
+main "$@"
 # vim: ts=4 :
diff --git a/trunk/dynusers/bash/install_fail.bash.in b/trunk/dynusers/bash/install_fail.bash.in
--- a/trunk/dynusers/bash/install_fail.bash.in
+++ b/trunk/dynusers/bash/install_fail.bash.in
@@ -18,9 +18,8 @@ main() {
 	# Currently, we expect the following:
 	local eusers=${1} egroups=${2} pkgname=${3} userspace=${4} root=${5:-/}
 
-	[[ -z "${pkgname}" || -z "${userspace}" ]] \
-		&& die "Script expects 4 arguments: \"new users\" "\
-			"\"new groups\" pkgname userspace"
+	[[ -z "${pkgname}" ]] && die "missing required arg: pkgname"
+	[[ -z "${userspace}" ]] && die "missing required arg: userspace"
 
 	# Remove this instance of pkgname from the database
 	"${SCRIPTDIR}/db.bash" del "${pkgname}" "${root}"
@@ -28,13 +27,19 @@ main() {
 	# If this install process created any users, then we should now remove
 	# them.
 	for x in ${eusers} ; do
-		"${SCRIPTDIR}/deluser.bash" "${x}" "${pkgname}" \
-			"${userspace}" "${root}"
+		if [[ ! -s "${DBDIR}/user/${x}" ]] ; then
+			"${SCRIPTDIR}/deluser.bash" "${x}" "${pkgname}" \
+				"${userspace}" "${root}" \
+				|| die "deluser ${x} failed"
+		fi
 	done
 
 	for x in ${egroups} ; do
-		"${SCRIPTDIR}/delgroup.bash" "${x}" "${pkgname}" \
-			"${userspace}" "${root}"
+		if [[ ! -s "${DBDIR}/user/${x}" ]] ; then
+			"${SCRIPTDIR}/delgroup.bash" "${x}" "${pkgname}" \
+				"${userspace}" "${root}" \
+				|| die "delgroup ${x} failed"
+		fi
 	done
 }
 
@@ -43,5 +48,5 @@ if [[ "${1}" == "--test" ]] ; then
 	exit 0
 fi
 
-main $@
+main "$@"
 # vim: ts=4 :
