Make all auth scripts match the new style (each contains a single function). Update the {add,del}{user,group} scripts to match.
git-svn-id: file:///tank/backups/everglades/var/svn/creandus@155 1c067ae2-9913-0410-8806-fa90ff404265

diff --git a/trunk/dynusers/bash/addgroup.bash.in b/trunk/dynusers/bash/addgroup.bash.in
--- a/trunk/dynusers/bash/addgroup.bash.in
+++ b/trunk/dynusers/bash/addgroup.bash.in
@@ -90,8 +90,8 @@ main() {
 		then
 			echo "Running ${x}-${userspace}-group${action}..."
 			. "${SCRIPTDIR}/auth/${x}-${userspace}-group${action}.bash"
-			"${x}-${userspace}-group${action}" "${groupid}" \
-				|| die "group${action} failed"
+			"${x}-${userspace}-group${action}" "${groupid}" "${newgroup}" \
+				"${root}" || die "group${action} failed"
 		else
 			echo -n "Auth backend ${x} with " >&2
 			echo -n "userspace ${userspace} " >&2
