Make sure that failure to source any of our helper functions' scripts is fatal. Also, make sure we die if calls to {user,group}{add,mod,del} functions fail.
git-svn-id: file:///tank/backups/everglades/var/svn/creandus@153 1c067ae2-9913-0410-8806-fa90ff404265

diff --git a/trunk/dynusers/bash/addgroup.bash.in b/trunk/dynusers/bash/addgroup.bash.in
--- a/trunk/dynusers/bash/addgroup.bash.in
+++ b/trunk/dynusers/bash/addgroup.bash.in
@@ -10,13 +10,13 @@
 SCRIPTDIR=${SCRIPTDIR:-@SCRIPTDIR@}
 
 # Load the basic configuration.
-. "${SCRIPTDIR}/common/config.bash"
-. "${SCRIPTDIR}/common/functions.bash"
+. "${SCRIPTDIR}/common/config.bash" || exit 1
+. "${SCRIPTDIR}/common/functions.bash" || exit 1
 
 # We make use of egetent. 
-. "${SCRIPTDIR}/common/getent.bash"
+. "${SCRIPTDIR}/common/getent.bash" || exit 1
 # Reads the proper data file for the desired group
-. "${SCRIPTDIR}/common/read_groupdata.bash"
+. "${SCRIPTDIR}/common/read_groupdata.bash" || exit 1
 
 main() {
 	# Read the command line arguments.
@@ -90,7 +90,8 @@ main() {
 		then
 			echo "Running ${x}-${userspace}-group${action}..."
 			. "${SCRIPTDIR}/auth/${x}-${userspace}-group${action}.bash"
-			"${x}-${userspace}-group${action}" "${groupid}"
+			"${x}-${userspace}-group${action}" "${groupid}" \
+				|| die "group${action} failed"
 		else
 			echo -n "Auth backend ${x} with " >&2
 			echo -n "userspace ${userspace} " >&2
diff --git a/trunk/dynusers/bash/adduser.bash.in b/trunk/dynusers/bash/adduser.bash.in
--- a/trunk/dynusers/bash/adduser.bash.in
+++ b/trunk/dynusers/bash/adduser.bash.in
@@ -10,13 +10,13 @@
 SCRIPTDIR=${SCRIPTDIR:-@SCRIPTDIR@}
 
 # Load the basic configuration.
-. "${SCRIPTDIR}/common/config.bash"
-. "${SCRIPTDIR}/common/functions.bash"
+. "${SCRIPTDIR}/common/config.bash" || exit 1
+. "${SCRIPTDIR}/common/functions.bash" || exit 1
 
 # Read the proper data file for the desired user
-. "${SCRIPTDIR}/common/read_userdata.bash"
+. "${SCRIPTDIR}/common/read_userdata.bash" || exit 1
 # We make use of egetent:
-. "${SCRIPTDIR}/common/getent.bash"
+. "${SCRIPTDIR}/common/getent.bash" || exit 1
 
 main() {
 	# Read the command line arguments.
@@ -101,7 +101,8 @@ main() {
 			echo "Running ${x}-${userspace}-user${action}..."
 			. "${SCRIPTDIR}/auth/${x}-${userspace}-user${action}.bash"
 			"${x}-${userspace}-user${action}" "${userhome}" "${usergroups}" \
-				"${usershell}" "${userid}" "${usercomment}" "${username}"
+				"${usershell}" "${userid}" "${usercomment}" "${username}" \
+				|| die "user${action} failed"
 		else
 			echo "Auth backend ${x} with userspace ${userspace}" \
 			"not supported by this script." 1>&2
diff --git a/trunk/dynusers/bash/delgroup.bash.in b/trunk/dynusers/bash/delgroup.bash.in
--- a/trunk/dynusers/bash/delgroup.bash.in
+++ b/trunk/dynusers/bash/delgroup.bash.in
@@ -9,8 +9,8 @@
 SCRIPTDIR=${SCRIPTDIR:-@SCRIPTDIR@}
 
 # Load the basic configuration
-. "${SCRIPTDIR}/common/config.bash"
-. "${SCRIPTDIR}/common/functions.bash"
+. "${SCRIPTDIR}/common/config.bash" || exit 1
+. "${SCRIPTDIR}/common/functions.bash" || exit 1
 
 main() {
 	# Read the command line arguments.
@@ -26,8 +26,10 @@ main() {
 	for x in ${GROUP_BACKENDS} ; do
 		if [[ -e "${SCRIPTDIR}/auth/${x}-${userspace}-groupdel.bash" ]]
 		then
-			echo "Running ${i}-${userspace}-groupdel..."
+			echo "Running ${x}-${userspace}-groupdel..."
 			. "${SCRIPTDIR}/auth/${x}-${userspace}-groupdel.bash"
+			"${x}-${userspace}-groupdel" "${deadgroup}" \
+				|| die "groupdel failed"
 		else
 			echo "Auth backend ${x} with userspace ${userspace}" \
 				"not supported by this script." >&2
